[project]
name = "telegramrss"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ebooklib>=0.19",
    "fastapi>=0.115.12",
    "ipython>=9.1.0",
    "markdown>=3.8",
    "pysocks>=1.7.1",
    "ruff>=0.12.4",
    "telethon>=1.40.0",
    "uvicorn>=0.34.2",
]
